name: linting-building-testing
run-name: Test project
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v3

      # Step: Setup and configure Node.js
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step: Install dependencies
      - name: Install modules
        run: npm install

      # Step: TypeScript linting
      - name: Linting TypeScript
        run: npm run lint:ts

      # Step: CSS linting
      - name: Linting CSS
        run: npm run lint:scss

      # Step: Unit testing
      - name: Unit Testing
        run: npm run test:unit

      # Step: Build production project
      - name: Build Production Project
        run: npm run build:prod

      # Step: Build Storybook
      - name: build storybook
        run: npm run storybook:build

      # Step: Build Storybook
      - name: update files from storybook
        run: loki update --reactUri="file:./storybook-static"

      # Step: UI screenshot testing
      - name: screenshot testing
        run: npm run test:ui:ci

      # Step: Automatic deployment to hosting platform
#       - name: Deploy to Hosting Platform
#         run: |
          # Add your deployment commands here
          # For example, if you are using FTP:
          # npm install -g ftp-deploy
          # ftp-deploy --user $FTP_USER --password $FTP_PASSWORD --host $FTP_HOST --local-dir ./build --remote-dir /public_html